export const moviesTypes = {
    FETCH_BY_CATEGORY_SERIES:'FETCH_BY_CATEGORY_SERIES',
    SET_BY_CATEGORY_SERIES:'SET_BY_CATEGORY_SERIES',
    FETCH_BY_CATEGORY_SERIES_NO_DATA:'FETCH_BY_CATEGORY_SERIES_NO_DATA',
    FETCH_BY_CATEGORY_SERIES_ERROR:'FETCH_BY_CATEGORY_SERIES_ERROR',
    FETCH_BY_CATEGORY_MOVIE:'FETCH_BY_CATEGORY_MOVIE',
    SET_BY_CATEGORY_MOVIE:'SET_BY_CATEGORY_MOVIE',
    FETCH_BY_CATEGORY_MOVIE_NO_DATA:'FETCH_BY_CATEGORY_MOVIE_NO_DATA',
    FETCH_BY_CATEGORY_MOVIE_ERROR:'FETCH_BY_CATEGORY_MOVIE_ERROR',
    SEARCH_BY_TITLE:'SEARCH_BY_TITLE',
    SET_BY_TITLE:'SET_BY_TITLE',
    FETCH_BY_TITLE_NO_DATA:'FETCH_BY_TITLE_NO_DATA',
    FETCH_BY_TITLE_ERROR:'FETCH_BY_TITLE_ERROR'

}